
networks:
  default:
    name: ${NETWORK}
    external: true


services:

  docker-image-prune:
    image: docker:cli
    restart: ${SRV_RESTART_MODE:-always}
    command: tail -f /dev/null
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.docker-cli.schedule: "@every 7m"
      ofelia.job-exec.docker-cli.command: >
        sh -c 'docker image prune -a -f --filter "until=24h"'
    deploy:
      # endpoint_mode: dnsrr
      # mode: global
      # restart_policy:
      #   condition: ${SRV_RESTART_MODE:-any}
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_DOCKERCLI:-128M}
        reservations:
          memory: ${RES_RESER_MEM_DOCKERCLI:-64M}
          
  cron:
    image: mcuadros/ofelia:latest
    restart: ${SRV_RESTART_MODE:-always}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: daemon --docker
    labels:
      ofelia.job-local.test-job.schedule: "@every 1m"
      ofelia.job-local.test-job.command: >
        sh -c 'date'
    deploy:
      # endpoint_mode: dnsrr
      # mode: global
      # restart_policy:
      #   condition: ${SRV_RESTART_MODE:-any}
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_CRON:-128M}
        reservations:
          memory: ${RES_RESER_MEM_CRON:-64M}
