
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true


services:
  bytebase:
    image: bytebase/bytebase:latest
    container_name: bytebase
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/bytebase:/var/opt/bytebase
    ports:
      - ${PORT_BYTEBASE:-8080}:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.bytebase.rule=HostRegexp(`^bytebase\..*`)
      - traefik.http.routers.bytebase.tls=true
      - traefik.http.routers.bytebase.entrypoints=websecure
      - traefik.http.routers.bytebase.service=bytebase@docker
      - traefik.http.services.bytebase.loadbalancer.server.port=8080
    healthcheck:
      disable: true
      test: ["CMD", "curl --fail http://localhost:8080/healthz || exit 1"]
      interval: 1m30s
      timeout: 60s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      placement:
        constraints: [node.host == manager]
      resources:
        limits:
          memory: ${RES_LIMIT_MEM}
        reservations:
          memory: ${RES_RESER_MEM}