
networks:
  default:
    name: ${NETWORK}
    external: true

services:
  acme:
    image: neilpang/acme.sh:3.0.6
    restart: ${SRV_RESTART_MODE:-always}
    volumes:
      - ${DATA}/acme:/acme.sh
      - ${DATA}/acme/entry.sh:/tmp/entry.sh:ro
    environment:
      DOMAIN: ${DOMAIN}
      DOMAINS: ${DOMAINS}
      ACME_DNS: ${ACME_DNS}
      CONFIG_HASH: ${ACME_CONFIG_HASH:-}
    command: ["sh", "/tmp/entry.sh"]
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.acme-renew.schedule: "@daily"
      ofelia.job-exec.acme-renew.command: >
        sh -c "
        acme.sh --home /acme.sh --renew-all >> /acme.sh/renew.log 2>&1
        "
    deploy:
      # endpoint_mode: dnsrr
      # restart_policy:
      #   condition: ${SRV_RESTART_MODE:-any}
      # placement:
      #   constraints:
      #     - node.labels.app_acme == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_ACME:-128M}
        reservations:
          memory: ${RES_RESER_MEM_ACME:-64M}