

# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true

services:

  kibana:
    container_name: kibana
    image: bitnami/kibana:latest
    restart: ${SRV_RESTART_MODE:-always}
    ports:
      - "${PORT_KIBANA:-5601}:5601"
    environment:
      - "TZ=Asia/Shanghai"
      - "I18N_LOCALE=zh-CN"
      - "KIBANA_ELASTICSEARCH_URL=elasticsearch"
      - "KIBANA_ELASTICSEARCH_PORT_NUMBER=9200"
      - "KIBANA_PASSWORD=${PASSWORD}"
      - "KIBANA_CREATE_USER=true"
      - "KIBANA_ELASTICSEARCH_PASSWORD=${PASSWORD}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.kibana.rule=HostRegexp(`^kibana\..*`)
      - traefik.http.routers.kibana.tls=true
      - traefik.http.routers.kibana.entrypoints=websecure
      - traefik.http.routers.kibana.service=kibana@docker
      - traefik.http.services.kibana.loadbalancer.server.port=5601
      - traefik.http.services.kibana.loadBalancer.passHostHeader=true
      - traefik.http.middlewares.kibana.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.kibana.headers.contentSecurityPolicy=upgrade-insecure-requests
    deploy:
      placement:
        constraints: 
          - node.role == manager
      resources:
        limits:
          memory: ${RES_LIMIT_MEM}
        reservations:
          memory: ${RES_RESER_MEM}

