
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true


services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.120.0
    container_name: vmdb
    restart: always
    ports:
      - ${PORT_VICTORIAMETRICS_HTTP}:8428
      - ${PORT_VICTORIAMETRICS_INFLUX}:8089
      - ${PORT_VICTORIAMETRICS_INFLUX}:8089/udp
      - ${PORT_VICTORIAMETRICS_GRAPHITE}:2003
      - ${PORT_VICTORIAMETRICS_GRAPHITE}:2003/udp
      - ${PORT_VICTORIAMETRICS_OPENTSDB}:4242
    volumes:
      - ${DATA}/vmdb:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
    deploy:
      placement:
        constraints: [node.host == manager]
      resources:
        limits:
          memory: ${RES_LIMIT_MEM}
        reservations:
          memory: ${RES_RESER_MEM}