
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true


services:

  mysql8:
    image: mysql:8.0-oracle
    container_name: mysql8
    restart: always
    privileged: true
    ports:
      - "${PORT_MYSQL8}:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/mysql8/data:/var/lib/mysql
      - ${DATA}/mysql8/log:/var/log/mysql
      - ${DATA}/mysql8/conf/my.cnf:/etc/mysql/my.cnf
    #  - /opt/data/mariadb/config/my.cnf:/etc/mysql/my.cnf 
    environment:
      TIMEZONE: Asis/Shanghai
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: public
    command:
      --innodb-flush-method=fsync
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    deploy:
      placement:
        constraints: [node.host == manager]
      resources:
        limits:
          memory: ${RES_LIMIT_MEM}
        reservations:
          memory: ${RES_RESER_MEM}
