
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true


services:
  waline:
    image: lizheming/waline:latest
    container_name: waline
    restart: ${SRV_RESTART_MODE:-always}
    network_mode: ${SRV_NETWORK_MODE:-${NETWORK_MODE_WALINE:-}}
    ports:
      - "${PORT_WALINE:-8360}:8360"
    environment:
      MYSQL_DB: waline
      MYSQL_HOST: mysql8
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8360/"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.http.routers.waline.rule=HostRegexp(`^waline\..*`)
      - traefik.http.routers.waline.tls=true
      - traefik.http.routers.waline.entrypoints=websecure
      - traefik.http.routers.waline.service=waline@docker
      - traefik.http.services.waline.loadbalancer.server.port=8360
      - traefik.http.services.waline.loadBalancer.passHostHeader=true
      - traefik.http.middlewares.waline.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.waline.headers.contentSecurityPolicy=upgrade-insecure-requests
    deploy:
      placement:
        constraints: [node.host == manager]
      resources:
        limits:
          memory: ${RES_LIMIT_MEM}
        reservations:
          memory: ${RES_RESER_MEM}