services:
  hiddify:
    #only for local build and development
    #build: .

    #latest release version
    image: ghcr.io/hiddify/hiddify-manager:latest

    #latest beta version
    #image: ghcr.io/hiddify/hiddify-manager:beta

    #latest build of current development
    #image: ghcr.io/hiddify/hiddify-manager:dev

    #specific version
    #image: ghcr.io/hiddify/hiddify-manager:v10.80.0
    ports:
      - 443:443
      - 80:80
      - "11000-60000"  #for custom protocols like hysteria tuic wiregaurd 
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
       - ./docker-data/:/hiddify-data/
    environment:
      REDIS_URI_MAIN: 'redis://:${PASSWORD}@redis:6379/0'
      REDIS_URI_SSH: 'redis://:${PASSWORD}@redis:6379/1'
      SQLALCHEMY_DATABASE_URI: 'mysql+mysqldb://root:${PASSWORD}@mysql/hiddifypanel?charset=utf8mb4'

    
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    command: ["redis-server", "--requirepass", "${PASSWORD}"]
    volumes:
      - ./docker-data/redis_data:/data                # Persistent storage for Redis data
    