
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true


services:

  metersphere:
    image: metersphere/metersphere
    container_name: metersphere
    restart: unless-stopped
    privileged: true
    ports:
      - "${PORT_METERSPHERE}:8080"
      - "${PORT_METERSPHERE_SSL}:443"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql8
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${PASSWORD}
      - DB_NAME=metersphere
    volumes:
      - ${DATA}/metersphere/data:/data
      - ${DATA}/metersphere/logs:/logs
    deploy:
      placement:
        constraints: [node.host == manager]
      resources:
        limits:
          memory: ${RES_LIMIT_MEM}
        reservations:
          memory: ${RES_RESER_MEM}
